#!/usr/bin/env python3

import sys

my_seq1 = '---------AGCA---------CCCTCCCACCTCATCCCACCCTTCTGATCTCAATCCAACGTCGCATC--------TCCACCGTCTCGCGG-ATCGACC--------------CAGCGAAGTCCCTCCCGC--CCCCAAAGTCCCCCAAATCTTGCAGTTC--------------CCTCCTAAATCCTCCCC-ATATAAACCAACCCCC-CGCCCTCAGATCCCTAAT--------------------------------CCCATCGCAAGCATCAGACT-----CCCTCCAAAGCAG------------------------GCAGCAGCTCCTCTTCTTCCTAATCACACTATCTCGGAGAGGAGCGGCCATGTCTGGGCGCGACAAGGGCGGCAAGGGGCTGGGCAAGGGCGGCGCCAAGCGGCACCGGAAGGTCCTCCGCGACAACATCCAGGGCATCACCAAGCCGGCGATCCGGAGGCTGGCCAGGAGGGGCGGCGTGAAGCGCATCTCCGGCCTCATCTACGAGGAGACCCGCGGCGTCCTCAAGATCTTCCTCGAGAACGTCATCCGCGACGCCGTCACCTACACCGAGCACGCCCGCCGCAAAACCGTCACCGCCATGGACGTCGTCTACGCGCTCAAGCGCCAGGGCCGCACCCTCTACGGCTTCGGAGGCTAGATTTGTGTGGTGAAGCAACTTCCTCGTTTGCTCTGTGAT------CTGTGCTGTCGTAGATGAGATTTACTGATTT---GGCGTGCGCCGGTTGTATTCTGTCAT---GGGGTTCAGTGGGCTGTGTA------------ATACCT--------TGCTCTGTACT--TCTGTTCAATGCAA-TCACTTCTATTCTGAA---------'

my_seq2 = 'TCTAGAGATGGCGCCATTTGATTCCAGCAGCCACAAAGC----------ACTAGAACAATCGATGCTAAGAGGTGACAGGAAAAACAGGCTGCAAAGACCCAGACAATGGAATGCAGCGGTGGTCAGCCTAAAACACTGTAGAAGGGCAAGATGAGCTGAGTAATTTTTAACTGGGCATCATTTTTAGAAACTGGAGTTTAAGTACCCCCTTTTCCATTTTTTCCTGAAGTCGTGGGCAGGGCGCAAGGTCTGTGAATCGGCCGACCGGATGCAGCTGGTGTGGAGAGTTCCCAATCAGGTCCGATTTATTACTATATAAAGTACTGCTGCGAGGCT--TGCCGTGTTGCA---TTTTGTTTAGTACAAGACATGTCTGGGCGCGGCAAAGGCGGGAAGGGTCTGGGCAAAGGAGGCGCTAAGCGCCACCGCAAAGTTCTGCGCGACAACATTCAGGGCATCACCAAGCCCGCCATCCGACGCCTGGCACGGCGTGGAGGCGTTAAGCGCATCTCAGGCCTTATATACGAGGAGACACGCGGAGTTCTTAAAGTGTTTTTGGAGAATGTAATCCGCGATGCAGTTACCTACACGGAGCACGCCAAACGCAAGACAGTCACAGCCATGGACGTGGTTTACGCGCTCAAGCGCCAGGGCCGCACCCTGTATGGCTTTGGCGGCTGAGTGTT------TTACTTACTTACACGGTTCCTCAAAGGCCCTTCTCAGGGCCACCCATGAAGTCTGTGAAAGAGCTGTAGACTAAAGATAGTTAATTTCTTAAGAACACTTAAACGTATGGCAGTTTTGGCAAATTAGCGATTCCACATAAGCAGTCGCTGAAGTTTGAGGTTCGGTGCCCCTTTCAGCATTACTTAGTGGTTAAAA'

print(len(my_seq1))
print(len(my_seq2))

same = 0
diff = 0

for n in range(len(my_seq1)):
    if my_seq1[n] == my_seq2[n]:
        same += 1
    else:
        diff += 1

print(f'Percent similarity is {same/(same+diff):.2%}')